stackbase/urls.py
from django.urls import path
from . import views

app_name = 'stackbase'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),

    # CRUD Function
    path('questions/', views.QuestionListView.as_view(), name="question-lists"),
    path('questions/new/', views.QuestionCreateView.as_view(), name="question-create"),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name="question-detail"),
    path('questions/<int:pk>/update/', views.QuestionUpdateView.as_view(), name="question-update"),
    path('questions/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name="question-delete"),
    path('questions/<int:pk>/comment/', views.AddCommentView.as_view(), name="question-comment"),
    path('like/<int:pk>', views.like_view, name="like_post")

]

stackprj/urls.py
from django.contrib import admin
from django.urls import path, include
from stackusers import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stackbase.urls')),

    # Authentication System
    path('register/', user_view.register, name="register"),
    path('login/', auth_view.LoginView.as_view(template_name="stackusers/login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="stackusers/logout.html"), name='logout'), 

    # Profile system
    path('profile/', user_view.profile, name="profile"),
    path('profile/update/', user_view.profile_update, name="profile_update")
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Softwarica Asks - Where Students Learn, Share, &amp; Build Careers</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    
</head>
<body>

<header>

<div class="nav-container">
    <nav>
        <div class="nav-brand">
            <div class="hamburger-menu-container">

                <div class="hamburger-menu">
                    <div class="line"></div>
                    <div class="line"></div>
                    <div class="line"></div>
                </div>
                <div class="nav-dropdown-menu">
                    <a href="#" class="current-link">Home</a>
                    <h5>Public</h5>
                    <ul class="nav-ul">
                        <li class="nav-item">
                            <i class="fas fa-globe-europe"></i>
                            <a href="" class="nav-link">SoftwaricaAsks</a>
                        </li>
                        <li class="nav-item"><a href="#" class="nav-link">Tags</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Users</a></li>
                    </ul>
                    <h5>Find a Job</h5>
                    <ul class="nav-ul">
                        <li class="nav-item"><a href="#" class="nav-link">Jobs</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Companies</a></li>
                    </ul>
                    <h5>Teams <a href="#" >What's this ?</a></h5>
                    <a href="#" class="nav-link">
                        <i class="fas fa-briefcase"></i>
                        <span>Thankyou for Visiting!</span>
                    </a>
                </div>
            </div>

            <a href="" class="nav-icon">
                <i class="fab"></i>
                <a href="{% url 'stackbase:home' %}" style="text-decoration: none; color: black;"><div class="nav-icon-text">Softwarica <span class="nav-bold-text">Asks</span></a>
                <!-- <div class="nav-icon-text">stack <span class="nav-bold-text">overflow</span> -->

                
                </div>
            </a>
        </div>
        <div class="nav-base-links">
            <ul>
                <li><a href="#services">Services</a></li>
                <li><a href="#members">About us</a></li>
                <li><a href="#contact">Contact us</a></li>
                <li><a href="https://softwarica.edu.np/#courses">Academics</a></li>
            </ul>
        </div>
        <div class="nav-search">
            <div class="search-container">
                <i class="fas fa-search"></i>
                <form action="" method="GET">
                    <input type="text" id="" name="search-area" placeholder="Search...">
                    <button type="submit" style="margin-left: 340px; border-radius: 25px; border: none; padding: 8px;">Search</button>
                </form>
            </div>
            <div class="search-hints">
                <div class="search-arrow-up"></div>
                <div class="search-hint-body">
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>[tag] </span> search within a tag</div>
                        <div class="hint-text"><span>user:1234 </span>  search by author</div>
                        <div class="hint-text"><span>"words here"</span> exact phrase </div>
                    </div>
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>answers:0</span> unanswered questions</div>
                        <div class="hint-text"><span> score:3  </span> posts with a 3+ score</div>
                    </div>
                </div>
                <div class="search-hint-footer">
                    <a href="#" class="btn">Ask a question</a>
                    <a href="#" class="search-help">Search help</a>
                </div>
            </div>

        </div>
        <div class="nav-right-buttons">
            <div class="search-btn">
                <i class="fas fa-search"></i>
            </div>
            {% if user.is_authenticated %}
                <a href="{% url 'profile' %}" class="btn btn-login">Profile</a>
                <a href="{% url 'logout' %}" class="btn btn-register">Logout</a> 
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-login">Log in</a>
                <a href="{% url 'register' %}" class="btn btn-register">Sign up</a> 
            {% endif %}
        </div>
    </nav>
</div>
<!-- <h1 style="font-size: 20px;">hello</h1> -->
    <div style="margin-top: 10px;">
        {% if messages %}
        {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        <h4 style="text-align: center;">{{ message }}</h4>
      </div>
      {% endfor %}
    {% endif %}
    </div>

        
</header>

<!-- Add block content here -->
<!-- Add enbdblock content here -->

{% block content %}

{% endblock content %}

<section class="jobs">
    <div class="container">

        <div class="jobs-content">
            <h3 class="jobs-title" id="contact">Contact Us</h3>
            <div class="jobs-body">
                    <div class="jobs-items">
                        <div class="column">
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-tech.svg?v=42f011c01763" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Phone</p>
                                <h6> 4525661 </h6>
                            </div>
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-salary.svg?v=401840ff8931" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Email</p>
                                <h6><span> softwarica@gmail.com </span> <a href="mailto:frontdesk@softwarica.com"> </h6>
                            </div>
                        </div>
                        <div class="column">
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-visa.svg?v=1f3acc6dc772" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Address</p>
                                <h6>
                                    <span>Kathmandu, Nepal</span>
                                </h6>
                            </div>
                        </div>
                    </div>
                    <div class="jobs-btn">
                        <div class="btn btn-orange jobs-btn">Join Us now</div>
                    </div>
            </div>
        </div>
    </div>
</section>

<section id="footer2" style="background-image: linear-gradient(60deg, #29323c 0%, #485563 100%); align-items: center; min-height: 200px; flex-direction: column; padding-top: 15px; padding-bottom: 10px;">
    <div class="footer container" style="text-align: center; ">
    <div class="brand">
        <h1 style="font-size: 25px; text-transform: none; color: white; space-between:none;"><span style="color: crimson;">S</span>oftwarica <span style="color: crimson;">A</span>sks</h1>
    </div>
    <h2 style="color: white; font-weight: 500; font-size: 18px; letter-spacing: 0.1rem; margin-top: 10px; margin-bottom: 10px;">Together we succeed</h2>
    <ul class="social-icon" style="justify-content:center; display: flex; flex-direction: row; padding-right: 10px; list-style: none;">
        <li><div class="facebook">
        <a href="https://www.facebook.com/softwarica.nepal"><img src="https://img.icons8.com/color/48/000000/facebook.png" style ="width: 40px; height: 40px; filter: grayscale(1); transition: 0.3s ease filter; margin: 0 5px;"></a>
        </div></li>
        <li><div class="instagram">
        <a href="https://www.instagram.com/softwarica.college/"><img src="https://img.icons8.com/fluency/48/000000/instagram-new.png" style ="width: 40px; height: 40px; filter: grayscale(1); transition: 0.3s ease filter; margin: 0 5px;"></a>
        </div></li>
        <li><div class="twitter">
        <a href="https://twitter.com/SoftwaricaNepal"><img src="https://img.icons8.com/color/48/000000/twitter-squared.png" style ="width: 40px; height: 40px; filter: grayscale(1); transition: 0.3s ease filter; margin: 0 5px;"></a>
        </div></li>
        <li><div class="youtube">
            <a href="https://www.youtube.com/c/SOFTWARICACOLLEGEOFITANDECOMMERCEKathmandu"><img src="https://img.icons8.com/fluency/48/000000/youtube-squared.png" style ="width: 40px; height: 40px; filter: grayscale(1); transition: 0.3s ease filter; margin: 0 5px;"></a>
        </div></li>
    </ul>
    <p style="color: white; font-size: 12px; align-items: center;">Softwarica College of IT & E-Commerce. Copyrights @ 2022. All Rights Reserved</p>
    </div>
</section>



<!-- <script src="assets/js/main.js"></script> -->
<script src="{% static 'main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<section class="hero">
    <div class="hero-content">
        <h1 class="hero-title">Welcome <span></span></h1>
        <h1 class="hero-title">To SoftwaricaAsks! <span></span></h1>
        <h1 class="hero-title">Ask us <span></span></h1>
        <p class="hero-paragraph">
            Together we succeed
        </p>
        <div class="hero-options">
            <a href="{% url 'stackbase:question-lists' %}" class="btn btn-developers" style="margin-left: 5px;">Join Community</a>

        </div>
    </div>
</section>


<section class="for-developers">
   <div class="container">
       <div class="section-head">
           <h2 class="section-title" id="services">Services
           </h2>
           <div class="section-line"></div>
           <p class="section-description">SoftwaricaAsks is an <a href="#">open platform</a> for the students of Softwarica College. We help you find solutions to all of your queries.
           </p>
       </div>
       <div class="options">
           <div class="option">
               <div class="option-icon">
                   <img src="https://cdn.sstatic.net/Img/home/public-qa.svg?v=d82acaa7df9f" alt="Public Q & A">
               </div>
               <div class="option-title">
                   Coding Help
               </div>
               <div class="option-description">
                Our Codementor feature helps you to get the best of your coding situation. We provide you the best of the best coding solutions. Building a strong Coding Community is how we will help you to get all the solutions to your coding problems.
                   <a href="#">Sign up</a> for an account.
               </div>
               <div class="option-button">
                   <a href="#" class="option-link btn btn-dark-blue">
                       Browse questions
                   </a>
               </div>
           </div>
           <div class="option">
               <div class="option-icon">
                   <img src="https://cdn.sstatic.net/Img/home/private-qa.svg?v=2c1de180b6d7" alt="Private Q & A">
               </div>
               <div class="option-title">
                   Module Questions
               </div>
               <div class="option-description">
                Softwarica College's modules are designed to help you to get the best of your learning situation. Any help needed are provided by you to you. Creating a strong community for module related questions and answers is going to be very helpful for your learning.
               </div>
               <div class="option-button">
                   <a href="#" class="option-link btn btn-orange">
                       Go
                   </a>
               </div>
           </div>
           <div class="option">
               <div class="option-icon">
                   <img src="https://cdn.sstatic.net/Img/home/jobs.svg?v=931d6c0863ee" alt="Browse jobs
">
               </div>
               <div class="option-title">
                   Jobs and Career
               </div>
               <div class="option-description">
                Guidance will be provided to you for your career. We will also provide you jobs in the college for polishing your skills. Personal Career guidance appointment can also be managed if necessary. In-College jobs will be provided to the interested ones.


               </div>
               <div class="option-button">
                   <a href="#" class="option-link btn btn-dark-blue">
                       Ask now
                   </a>
               </div>
           </div>
       </div>
   </div>
</section>

<section class="for-businesses">
    <div class="container">
        <div class="section-head">
            <h2 class="section-title">For students, by students</h2>
            <div class="section-line"></div>
            <p class="section-description">You can ask your own question to the community. The best answers will be given with votes and comments. Strong community with smart students will be participating in the forum for getting and giving help.</p>
        </div>



        <div class="options">
            <div class="option">
                <div class="option-icon">
                    <img src="https://cdn.sstatic.net/Img/home/private-questions.svg?v=a4f1cfb08f7e" alt="Private Q&A">
                </div>
                <div class="option-description">
                    Share your ideas
                </div>
            </div>
            <div class="option">
                <div class="option-icon">
                    <img src="https://cdn.sstatic.net/Img/home/find-candidate.svg?v=9099aa106ad3" alt="Talent solutions">
                </div>
                <div class="option-description">
                    Make new friends
                </div>
            </div>
            <div class="option">
                <div class="option-icon">
                    <img src="https://cdn.sstatic.net/Img/home/accelerate.svg?v=9d4c2786ff02" alt=" Advertising platform">
                </div>
                <div class="option-description">
                    Earn votes, get recognized
                </div>
            </div>
        </div>


    </div>
</section>


<section class="questions">
    <div class="container">
       <div class="questions-content">
           <div class="questions-header">
               <h3 class="question-title">Don't hesitate to ask us</h3>
           </div>
           <div class="questions-body">
               <div class="questions-body-items">
                   <div class="questions-body-item" data-id="0">
                       <img src="https://cdn.sstatic.net/Img/home/ask-a-question.svg?v=f4f2050b0297" alt="" class="question-item-icon">
                       <div class="question-item-text">Add questions</div>
                       <div class="question-arrow-right"></div>
                   </div>
                   <div class="questions-body-item"  data-id="1">
                       <img src="https://cdn.sstatic.net/Img/home/votes.svg?v=748a8f48a8e2" alt="" class="question-item-icon">
                       <div class="question-item-text">Upvote and downvote</div>
                       <div class="question-arrow-right"></div>
                   </div >
                   <div class="questions-body-item"  data-id="2">
                       <img src="https://cdn.sstatic.net/Img/home/answer.svg?v=4cd8048a676c" alt="" class="question-item-icon">
                       <div class="question-item-text">Give answers like a pro</div>
                       <div class="question-arrow-right"></div>
                   </div>
               </div>
               <div class="questions-body-item-content">
                   <img src="https://cdn.sstatic.net/Img/home/illo-feats-vote.svg?v=9d2eb0efdc17" alt="" class="question-item-content-img">
                   <h4 class="question-item-content-text">
                       'Gaining Knowledge' is the first step to wisdom,
                       'Sharing it' is the first step to humanity.
                   </h4>
                   <a href="#" class="btn btn-orange question-item-content-btn">Create an account</a>
               </div>
               <div class="questions-body-items">
                   <div class="questions-body-item"  data-id="3">
                       <img src="https://cdn.sstatic.net/Img/home/tags.svg?v=913379eb09eb" alt="" class="question-item-icon">
                       <div class="question-item-text">Tag your questions</div>
                       <div class="question-arrow-left"></div>
                   </div>
                   <div class="questions-body-item"  data-id="4">
                       <img src="https://cdn.sstatic.net/Img/home/accept.svg?v=27d5be078970" alt="" class="question-item-icon">
                       <div class="question-item-text">Accept the solutions</div>
                       <div class="question-arrow-left"></div>
                   </div>
                   <div class="questions-body-item"  data-id="5">
                       <img src="https://cdn.sstatic.net/Img/home/get-recognized.svg?v=3b339d9aa10c" alt="" class="question-item-icon">
                       <div class="question-item-text">Learn and grow</div>
                       <div class="question-arrow-left"></div>
                   </div>
               </div>
           </div>
           <div class="questions-footer">
               <h3 class="question-title" id="members">Members</h3>
               <div class="questions-grid">
                   <div class="questions-grid-item">
                       <div class="grid-item-img">
                           <img src="https://img.freepik.com/premium-vector/brunette-man-avatar-portrait-young-guy-vector-illustration-face_217290-1035.jpg?w=1060" alt="">
                       </div>
                       <h4 class="grid-item-title">Crystal Shrestha</h4>
                       <p class="grid-item-description">Scrum Master, Front-end Developer, Back-end Developer
                       </p>
                   </div>
                   <div class="questions-grid-item">
                       <div class="grid-item-img">
                           <img src="https://img.freepik.com/free-vector/boy-using-smartphone-white-background_1308-50786.jpg?w=996&t=st=1659103641~exp=1659104241~hmac=74796595814af8ae8869d98c0891c9543662c3d57ebf37b527b105fd3e096263" alt="">
                       </div>
                       <h4 class="grid-item-title">Dipson Panta
                       </h4>
                       <p class="grid-item-description">Front-end Developer, Back-end Developer
                       </p>
                   </div>
                   <div class="questions-grid-item">
                       <div class="grid-item-img">
                           <img src="https://img.freepik.com/free-vector/young-woman-pink-dress-smiling_1450-140.jpg?w=1060&t=st=1659103758~exp=1659104358~hmac=6a267d8d38d446ff23b9c782dfab9f318346c86d39f1d603ecef6371d48000d7" alt="">
                       </div>
                       <h4 class="grid-item-title">Jasmine Osti
                       </h4>
                       <p class="grid-item-description">Support
                       </p>
                   </div>
                   <div class="questions-grid-item">
                       <div class="grid-item-img">
                           <img src="https://img.freepik.com/premium-vector/young-good-looking-man-doing-arm-crossed-pose-with-confident_97632-4855.jpg?w=740" alt="" >
                       </div>
                       <h4 class="grid-item-title">Ramesh Budha
                       </h4>
                       <p class="grid-item-description">Hospitalized
                       </p>
                   </div>
               </div>
           </div>
       </div>
    </div>
</section>




{% endblock content %}